// This file is autogenerated by Firebase Studio. Please do not edit manually.

import { FirebaseOptions } from 'firebase/app';

const firebaseConfig: FirebaseOptions = {
  apiKey: "AIzaSyB5kk0vWb09rVudiw-YrvGN2bQGbPtwSJw",
  authDomain: "xpressmart-453e5.firebaseapp.com",
  projectId: "xpressmart-453e5",
  storageBucket: "xpressmart-453e5.appspot.com",
  messagingSenderId: "42900264359",
  appId: "1:42900264359:web:daeaa1a61cf09738439282",
  measurementId: "G-EQMMVTXWCT"
};

export function getFirebaseConfig(): FirebaseOptions {
  if (!firebaseConfig || !firebaseConfig.apiKey) {
    throw new Error('Missing firebase config');
  }
  return firebaseConfig;
}
